"""
exxon_config.py
---------------------------
Auto-generated config for Exxon.
Generated by: llm_config_generator.py
Confidence: unknown
Notes: 

Review the column_map before using in production.
"""

CONFIG = {
    "supplier_name": "Exxon",
    "file_format": "xlsx",
    "contract_type": "Wholesale",
    "country": "MX",
    "file_extensions": [
        ".xlsx",
        ".xlsm"
    ],
    "date_source": "title_row",
    "date_patterns": [
        "(\\d{2}/\\d{2}/\\d{4})",
        "(\\d{8})"
    ],
    "date_format_primary": "%d/%m/%Y",
    "date_format_fallback": "%Y%m%d",
    "structure": "xlsx_table",
    "sheet_name": "Precios Exxon",
    "sheet_index": 0,
    "header_row": 2,
    "data_start": 3,
    "column_map": {
        "terminal": [
            "terminal"
        ],
        "product": [
            "producto",
            "product",
            "fuel",
            "combustible"
        ],
        "price": [
            "facturaci",
            "facturacion",
            "invoice",
            "precio final",
            "net price",
            "precio neto"
        ],
        "discount": [
            "descuento",
            "discount",
            "deduccion"
        ],
        "ref_price": [
            "referencia",
            "reference",
            "base price",
            "precio base"
        ]
    },
    "price_unit": "MXN_per_liter",
    "price_guardrails": {
        "min": 15.0,
        "max": 35.0
    },
    "terminal_pattern": "^(.+?)\\s*-\\s*(.+)$",
    "terminal_groups": {
        "terminal_id": 1,
        "terminal_name": 2
    },
    "product_map": {
        "regular": "Regular",
        "87": "Regular",
        "magna": "Regular",
        "premium": "Premium",
        "91": "Premium",
        "diesel": "Diesel"
    },
    "_uncovered_headers": [
        "Categoría Cuenta"
    ]
}