"""
g500_config.py
---------------------------
Auto-generated config for G500.
Generated by: llm_config_generator.py
Confidence: high
Notes: Clear tabular structure with separate columns for base price, discount, and final price. Terminal format includes ID and city name. Date extracted from filename in YYYYMMDD format.

Review the column_map before using in production.
"""

CONFIG = {
    "supplier_name": "G500",
    "file_format": "xlsx",
    "file_extensions": [
        ".xlsx"
    ],
    "contract_type": "volume_discount",
    "country": "MX",
    "date_source": "filename",
    "date_patterns": [
        "g500_(\\d{8})\\.xlsx"
    ],
    "date_format": "%Y%m%d",
    "structure": "xlsx_table",
    "sheet_name": "G500 Cotizacion",
    "sheet_index": 0,
    "header_row": 2,
    "data_start": 3,
    "column_map": {
        "terminal": [
            "punto_venta",
            "punto",
            "venta"
        ],
        "product": [
            "grado_combustible",
            "grado",
            "combustible"
        ],
        "price": [
            "costo_final_litro",
            "costo_final",
            "costo",
            "final"
        ],
        "discount": [
            "descuento_aplicado",
            "descuento"
        ],
        "ref_price": [
            "precio_base_mxn",
            "precio_base",
            "base"
        ]
    },
    "price_unit": "MXN_per_liter",
    "conversion_factor": 1.0,
    "price_guardrails": {
        "min": 15.0,
        "max": 35.0
    },
    "product_map": {
        "regular": "Regular",
        "premium": "Premium",
        "diesel": "Diesel"
    },
    "terminal_pattern": "^(G500-[A-Z]+-\\d+)\\s*-\\s*(.+)$",
    "terminal_groups": {
        "terminal_id": 1,
        "terminal_name": 2
    },
    "_generated_by": "llm_config_generator",
    "_confidence": "high",
    "_notes": "Clear tabular structure with separate columns for base price, discount, and final price. Terminal format includes ID and city name. Date extracted from filename in YYYYMMDD format."
}